sudo docker network create -d macvlan \
  --subnet=192.168.1.0/24 \
  --gateway=192.168.1.1 \
  -o parent=enp2s0 \
  lan_macvlan

sudo ip link add macvlan0 link enp2s0 type macvlan mode bridge
sudo ip addr add 192.168.1.50/24 dev macvlan0   # host için bir IP
sudo ip link set macvlan0 up


sudo docker compose down rabbitmq
sudo docker compose up -d rabbitmq


sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' rabbitmq-macvlan

sudo ip route add 192.168.1.60/32 dev macvlan0

host
ping -c2 192.168.1.60
curl -I http://192.168.1.60:15672
nc -vz 192.168.1.60 5672

vm
ping -c2 192.168.1.60
nc -vz 192.168.1.60 5672


sudo docker exec -it rabbitmq-macvlan bash -lc 'ss -lntp | egrep "(15672|5672)"'
sudo docker logs --tail=100 rabbitmq-macvlan
