"""
Django settings for pmys project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pmys.config import LDAP_DJANGO,DB
from pmys.config import LDAP_DJANGO, DB, LDAP as LDAP_API_CFG
import ldap

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secret_key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS = [
    "http://0.0.0.0:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://192.168.1.39:3000",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.1.39:3000",
]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'client',
    'policy',
    'user',
    'directory.apps.DirectoryConfig',
    "laps",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'pmys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pmys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB['NAME'],
        'USER': DB['USER'],
        'PASSWORD': DB['PASSWORD'],
        'HOST': DB['HOST'],
        'PORT': DB['PORT'],
    },
}

USE_DJANGO_AUTH_LDAP = True
try:
    import ldap as _python_ldap  # python-ldap
    from django_auth_ldap.config import LDAPSearch
except Exception:
    USE_DJANGO_AUTH_LDAP = False

if USE_DJANGO_AUTH_LDAP:
    AUTHENTICATION_BACKENDS = [
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

    AUTH_LDAP_SERVER_URI = LDAP_DJANGO["AUTH_LDAP_SERVER_URI"]
    AUTH_LDAP_BIND_DN = LDAP_DJANGO["AUTH_LDAP_BIND_DN"]
    AUTH_LDAP_BIND_PASSWORD = LDAP_DJANGO["AUTH_LDAP_BIND_PASSWORD"]

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        LDAP_DJANGO["AUTH_LDAP_USER_SEARCH_BASE"],
        _python_ldap.SCOPE_SUBTREE,
        "(uid=%(user)s)",
    )

    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    AUTH_LDAP_CREATE_USERS = True
else:
    AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]

LDAP_API = {
    "SERVER_URI": LDAP_API_CFG["SERVER"],
    "BIND_DN": LDAP_API_CFG["USER_DN"],
    "BIND_PASSWORD": LDAP_API_CFG["PASSWORD"],
    "BASE_DN": LDAP_API_CFG["BASE_DN"],

    "ORG_BASE_OU": os.getenv("LDAP_ORG_BASE_OU", ""),     
    "USER_PLACEMENT": os.getenv("LDAP_USER_PLACEMENT", "under_group"),  
    "GROUP_SCHEMA": os.getenv("LDAP_GROUP_SCHEMA", "groupOfNames"),     
    "LOCK_METHOD": os.getenv("LDAP_AUTH_LOCK_METHOD", "ppolicy"),       
}
LDAP_SYNC_INTERVAL = 60
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}